### ISSUE TITLE
Unobstructed view of photos

### ISSUE THREAD

**Issue by AstudilloMarillo** [BeFake-Client/BeFake#3]
This client is great! The only thing missing from this is being able to see each photo individually, without the other photo overlapping. BeUnblurred has integrated this feature nicely. You tap on the other photo to switch photos, and you tap on the current photo to toggle between having the other photo overlap or not. Any chance this could be implemented in BeFake?

**Comment by FH-DEV1** [comment]
I'll look into it although such a clean implementation would be really hard in our case. The best I can do is add a button in the 3 dots to hide/unhide secondary image.
I'll close this issue when the button is implemented.

**Comment by AstudilloMarillo** [comment]
That sounds like a decent solution. Shame it can't be as clean though.
