### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by KeyKatyu** [BeFake-Client/BeFake#7]
Hello,
The login still works but no longer access to the feed.

**Comment by FH-DEV1** [comment]
Thanks for the feedback !
I checked and it works for me. Can you tell me more about the issue (is it stuck infinitely loading or do you have an error message?).
Have you tried closing and reopening the website? I know it can get stuck sometimes for no apparent reason.

**Comment by KeyKatyu** [comment]
Thanks for your quick response, it works now!

**Comment by KeyKatyu** [comment]
Thanks for your quick response, it works now!
